### PR TITLE
Add myself as editor

### PR DESCRIPTION
**Pull request by jeisinger**
ptal

### CODE REVIEW

**Comment by annevk** [comment]
It might be time to create an acknowledgments section and put Joel there.

**Comment by jeisinger** [comment]
good point! I've added him as former editor

**Comment by devd** [comment]
Hey Jochen! I would still prefer to keep him as an editor for v1 of the spec. He did most of the work on this till now IMO. Depending on his participation, we can decide on v2 (unless the W3C insists that Snap's lack of membership makes this infeasible). thoughts? I think we did something similar in early versions of CSP.

**Comment by jeisinger** [comment]
I talked with @mikewest yesterday, as I'm not sure whether it's ok to continue to list Joel as affiliated with Google? @wseltzer can you advice what to do?

**Comment by wseltzer** [comment]
Hi @jeisinger , if all of Joel's contributions came while he was at Google, it's fine to list him with that former affiliation. (I hope we'll be able to bring him back in, too :)

**Comment by jeisinger** [comment]
Thanks! Updated the PR accordingly

**Pull request merged**
